= A docker image for Giblish

This repo enables an easy way to run https://github.com/rillbert/giblish[giblish] without a separate install of ruby or any other dependency from the https://github.com/search?q=asciidoctor&type=repositories[asciidoctor] toolchain.

A docker image is used to encapsulate all dependencies, and a helper script is provided to make it easy to run giblish. This makes it a very compact way of getting html or pdf output from a directory tree of asciidoc files.

== Using this repo

Prerequisites::

 * docker
 * git
 * a bash shell
 * internet access to the docker hub

To generate html files from a directory tree of adoc files using the default asciidoctor stylesheet, do the following:

[source,bash]
----
# clone this repo
$ git clone git@github.com:rillbert/giblish_dkr.git --depth=1

# build and run the image by using the helper script 'gendocs.sh'
$ giblish_dkr/gendoc.sh my_src_dir my_dst_dir
----

To generate pdf:s, add the `layout_dir` option to the `gendoc.sh` script. Within the layout dir, specify giblish flags in a `gibopts.txt` and/or layout assets in the same way as for giblish.

For example, to generate a pdf using the default asciidoctor stylesheet, do the following:

[source,bash]
----
# create a layout_dir and add a gibopts.txt file to specify pdf output.
$ mkdir my_layout_assets_dir
$ echo "-f pdf" > my_layout_assets_dir/gibopts.txt

# assuming you have cloned the repo as above, do
$ giblish_dkr/gendoc.sh my_layout_assets_dir my_src_dir my_dst_dir
----

The `layout_dir` can contain any number of files and subdirectories. It holds one or more css/yml for specifying different formats as well as images and other assets referenced by the css/yml files.

An example of a more complex layout_dir is shown below:

[source,bash]
----
.../layout_assets
      |--- fonts
          # example of fonts referenced by the css/yml
          |---- ZenKakuGothicNew-Black.ttf
          |---- ZenKakuGothicNew-Bold.ttf
          |---- ZenKakuGothicNew-Light.ttf
          |---- ZenKakuGothicNew-Medium.ttf
          |---- ZenKakuGothicNew-Regular.ttf
      # the file holding the flags for giblish
      |---- gibopts.txt
      # css/yml files as required by the asciidoctor toolchain, it is possible to have multiple
      # css/yml files for different layouts. It is the flags in the gibopts.txt file that
      # determines which css/yml file to use.
      |---- my_first_html_layout.css
      |---- my_first_pdf_layout.yml
      |---- my_second_html_layout.yml
      |---- my_second_pdf_layout.yml
      # ... assets for the layout, e.g. a logo file) referenced by the css/yml ...
      |---- logo.png
      # ...
----

== Re-using the scripts and layout assets

The `gendoc.sh` script is a generic wrapper for running giblish from the `rillbert/giblish:latest` docker image. One useful use case is:

 . copy and commit the `gendoc.sh` script to a directory in the git repo(s) from where you want to generate docs.
 . add and commit a `layout_dir` directory containing the layout assets and gibopts.txt file for each specific repo.

This way, you can easily generate docs with different layouts from different repos, and still keep the layout assets and gibopts.txt file in the repo where they belong.

== DISCLAIMER

This repo is not affiliated with the asciidoctor project in any way. It is a personal project to make it easier to use giblish.

It is provided as-is and I don't intend to provide a strict, versioned release cycle. I you find it useful, great! If you want more control, you can always fork it and tweak scripts and docker images to your liking


== Developing for this repo

To 'manually' build and publish the docker image, do the following:

----
# build the image
docker build -t rillbert/giblish .

# push to docker hub
docker login
# fill in user id/passwd

# push the image
docker push -t rillbert/giblish .
----
