= Use giblish via docker

This repo provides an easy way to run https://github.com/rillbert/giblish[giblish] without a separate install of ruby or any other dependency from the https://github.com/search?q=asciidoctor&type=repositories[asciidoctor] toolchain.

A docker image is used to encapsulate all dependencies and a helper script is provided to make it easy to run giblish via the docker image. This makes it a compact way of getting html or pdf output from a directory tree of asciidoc files.

== Quick start

To generate html files from a directory tree of adoc files using the default asciidoctor stylesheet, do the following:

[source,bash]
----
# clone this repo
git clone git@github.com:rillbert/giblish_dkr.git --depth=1

# run the helper script. It fetches the docker image and runs
# giblish on all adoc files under 'my_src_dir'  the output will
# be placed in 'my_dst_dir'
giblish_dkr/gendoc.sh my_src_dir my_dst_dir
----

Prerequisites::

 * docker
 * git
 * a bash shell
 * internet access to the docker hub

To use a custom theme, two things must be in place:

 . a directory containing all assets needed for the theme
 . a `gibopts.txt` file that contains the parameters that point to the theme (see below)


=== gibopts.txt

The docker image will parse a file named `gibopts.txt` for options to propagate to `giblish`.
The first `gibopts.txt` file found in:

  <src_dir>/gibopts.txt
  <layout_dir>/gibopts.txt

is used. If no `gibopts.txt` file is found, giblish is run without any options

For example, to generate a pdf using the default asciidoctor stylesheet, do one of the following:

[source,bash]
----
# 1. put a gibopts.txt file in the layout directory
$ mkdir my_layout_assets_dir
$ echo "-f pdf" > my_layout_assets_dir/gibopts.txt

# OR

# 2. put a gibopts.txt file in the top dir of the src (this file will
#    override any gibopts.txt file found in the layout directory)
$ echo "-f pdf" > my_src_dir/gibopts.txt

# run the helper script
$ giblish_dkr/gendoc.sh my_layout_assets_dir my_src_dir my_dst_dir

----

=== The `layout` directory

The `layout` directory can contain any number of files and subdirectories. It holds one or more css/yml for specifying different formats/themes as well as images and other assets referenced by the css/yml files.

An example of how a more complex `layout` directory could look like is provided below:

[source,bash]
----
.../layout_assets
      # fonts referenced by the css/yml
      |--- fonts
          |---- ZenKakuGothicNew-Black.ttf
          |---- ZenKakuGothicNew-Bold.ttf
          |---- ZenKakuGothicNew-Light.ttf
          |---- ZenKakuGothicNew-Medium.ttf
          |---- ZenKakuGothicNew-Regular.ttf

      # giblish options used if no gibopts.txt is found in the src dir
      # (e.g. "-f pdf -s my_second_pdf_layout")
      |---- gibopts.txt

      # css/yml files as required by the asciidoctor toolchain, it is possible to have multiple
      # css/yml files for different layouts. It is the flags in the gibopts.txt file that
      # determines which css/yml file to use.
      |---- my_first_html_layout.css
      |---- my_first_pdf_layout.yml
      |---- my_second_html_layout.yml
      |---- my_second_pdf_layout.yml

      # ... assets for the layout, e.g. a logo file) referenced from the css/yml files...
      |---- logo.png
      # ...
----

=== Markdown-to-asciidoc conversion

If the special parameter `--convert-md` is specified in `gibopts.txt`, the docker image invokes the `kramdoc` tool before invoking giblish. All markdown files found in the source directory will thus be converted to asciidoc before giblish is run.

== Re-using the scripts and layout assets

The `gendoc.sh` script is a wrapper to help running giblish from the `rillbert/giblish:latest` docker image. One useful use case is:

 . copy and commit the `gendoc.sh` script to a directory in the git repo(s) from where you want to generate docs.
 . add and commit a `layout` directory containing the layout assets and gibopts.txt file for each specific repo.

This way, you can easily generate docs with different layouts from different repos, and still keep the layout assets and gibopts.txt file in the repo where they belong.

== Notes

 * The `gendoc.sh` script is a wrapper for the `rillbert/giblish:latest` docker image. Found https://hub.docker.com/repository/docker/rillbert/giblish/general[here].

== DISCLAIMER

 * This repo is not affiliated with the asciidoctor project in any way. It is a personal project to make it easier to use giblish.
 * It is provided as-is and I don't intend to provide a strict, versioned release cycle. I you find it useful, great!
 * The same goes for the `rillbert/giblish:latest` docker image.
 * If you want more control, you can always fork it and tweak scripts and docker images to your liking


== Developing for this repo

To 'manually' build and publish the docker image, do the following:

----
# build the image
docker build -t rillbert/giblish .

# push to docker hub
docker login
# fill in user id/passwd

# push the image
docker push rillbert/giblish
----
